version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "5678:8080"
    volumes:
      - ./volumes/backend:/app
#      - ./volumes/avatars:/root/qqq
      - ./volumes/files:/app/files
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=java_docker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=superpassword
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./volumes/client:/usr/share/nginx/html
      - ./volumes/nginx.conf:/etc/nginx/conf.d/default.conf
